## 11-1

In [5]:
#11-1
import numpy as np
a=np.arange(0,6).reshape(3,2)
print(a)
a.sum(axis=0)

[[0 1]
 [2 3]
 [4 5]]


array([6, 9])

In [9]:
b=np.array(range(0,10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
c=np.array(range(0,10,2))
c

array([0, 2, 4, 6, 8])

In [13]:
print('c.shape=',c.shape)
print('c.ndim=',format(c.ndim))
print('c.dtype=',format(c.dtype))
print('c.size=',format(c.size))
print('c.itemsize=',format(c.itemsize))

c.shape= (5,)
c.ndim= 1
c.dtype= int32
c.size= 5
c.itemsize= 4


## 11-2 

In [11]:
a=np.array([23,45,67,7,2,30,34,82])
print('a=',format(a))

a= [23 45 67  7  2 30 34 82]


In [12]:
print('최댓값:',format(a.max()))

최댓값: 82


In [13]:
print('최솟값:',format(a.min()))

최솟값: 2


In [14]:
print('평균: ',format(a.mean()))

평균:  36.25


In [16]:
b=np.random.randint(0,100,size=10)
print('b=',format(b))

b= [47 75 96  2 18 11  6 82 88 37]


In [17]:
print('최댓값:',format(b.max()))

최댓값: 96


In [18]:
print('최솟값:',format(b.min()))

최솟값: 2


In [19]:
print('평균: ',format(b.mean()))

평균:  46.2


In [20]:
c=np.append(a,b)
print('c=',format(c))

c= [23 45 67  7  2 30 34 82 47 75 96  2 18 11  6 82 88 37]


## 11-3

In [15]:
a=np.arange(1,10,1).reshape(3,3)
print('a=',format(a))

a= [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
b=np.array([[2,2,2],[2,2,2],[2,2,2]])
print('b=',format(b))

b= [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [26]:
a+b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
a-b

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [28]:
a*b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [29]:
a/b

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [30]:
a@b

array([[12, 12, 12],
       [30, 30, 30],
       [48, 48, 48]])

In [31]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

## 11-4

In [32]:
a1=np.full((3,3),2)
print('a1=',a1)

a1= [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [33]:
a2=np.arange(1,13)
print('a2=',format(a2))

a2= [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
a3=np.arange(3,50,3)
a3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [35]:
a4=np.linspace(0,20,5)
a4

array([ 0.,  5., 10., 15., 20.])

## 11-5

In [36]:
a1=np.arange(1,13).reshape(2,6)
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [37]:
a2=np.arange(1,31).reshape(3,10)
a2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [38]:
a3=a2.reshape(6,5)
a3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [39]:
a4=np.transpose(a3)
a4

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

## 11-6

In [40]:
a=np.random.randint(0,100,size=15).reshape(3,5)
a

array([[97, 91, 84, 82, 77],
       [38, 46, 48, 64, 57],
       [45, 20, 70, 45, 93]])

In [41]:
print('a의 열방향 최댓값:',a.max(axis=1))
print('a의 열방향 최솟값:',a.min(axis=1))
print('a의 열방향 평균값:',a.mean(axis=1))

a의 최댓값: [97 64 93]
a의 최솟값: [77 38 20]
a의 평균값: [86.2 50.6 54.6]


In [42]:
print('a의 행방향 최댓값:',a.max(axis=0))
print('a의 행방향 최솟값:',a.min(axis=0))
print('a의 행방향 평균값:',a.mean(axis=0))

a의 행방향 최댓값: [97 91 84 82 93]
a의 행방향 최솟값: [38 20 48 45 57]
a의 행방향 평균값: [60.         52.33333333 67.33333333 63.66666667 75.66666667]


## 11-7

In [2]:
import numpy as np
a=np.arange(1,11)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
b=a[np.array([1,3,5,7])]
b

array([2, 4, 6, 8])

In [46]:
b=a[5:]
b

array([ 6,  7,  8,  9, 10])

In [48]:
c=a[:6]
c

array([1, 2, 3, 4, 5, 6])

In [11]:
d=a[0:3]
d

array([1, 2, 3])

In [51]:
e=a[::2]
e

array([1, 3, 5, 7, 9])

In [52]:
f=a[::-2]
f

array([10,  8,  6,  4,  2])

## 11-8

In [14]:
a=np.arange(0,24).reshape(4,3,2)
print('{:13s}{:5s}'.format('index','element'))
for i in np.ndindex(a.shape):
    print('{}{:7d}'.format(i,a[i]))

index        element
(0, 0, 0)      0
(0, 0, 1)      1
(0, 1, 0)      2
(0, 1, 1)      3
(0, 2, 0)      4
(0, 2, 1)      5
(1, 0, 0)      6
(1, 0, 1)      7
(1, 1, 0)      8
(1, 1, 1)      9
(1, 2, 0)     10
(1, 2, 1)     11
(2, 0, 0)     12
(2, 0, 1)     13
(2, 1, 0)     14
(2, 1, 1)     15
(2, 2, 0)     16
(2, 2, 1)     17
(3, 0, 0)     18
(3, 0, 1)     19
(3, 1, 0)     20
(3, 1, 1)     21
(3, 2, 0)     22
(3, 2, 1)     23


In [15]:
np.concatenate((a[0,0],a[1,0]),axis=0)

array([0, 1, 6, 7])

In [16]:
np.concatenate((a[0,0],a[2,1]),axis=0)

array([ 0,  1, 14, 15])

In [60]:
np.concatenate((a[0],a[1]),axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [61]:
np.concatenate((a[0],a[1]),axis=1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

## 11-9

In [62]:
a=np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
b=a[:,1]
b

array([ 1,  5,  9, 13])

In [64]:
c=a[2,1:]
c

array([ 9, 10, 11])

In [66]:
d=a[:2, :2]
d

array([[0, 1],
       [4, 5]])

In [67]:
e=a[1:3,1:3]
e

array([[ 5,  6],
       [ 9, 10]])

In [68]:
f=a[0:2,0:3].flatten()
f

array([0, 1, 2, 4, 5, 6])

In [69]:
g=a[2:,:].flatten()
g

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [70]:
h=np.concatenate((a[1,1:4],a[3, 1:4])).flatten()
h

array([ 5,  6,  7, 13, 14, 15])

## 11-10

In [73]:
import numpy as np
A=np.array([[1,1,-1],[2,-1,3],[1,2,1]],dtype='int32')
B=np.array([0,9,8],dtype='int32')
x=np.linalg.solve(A,B)
print('x={:4.1f}, y={:4.1f},z={:4.1f}'.format(x[0],x[1],x[2]))

x= 1.0, y= 2.0,z= 3.0


In [76]:
A=np.array([[1,1,-1],[2,-1,3],[1,2,1]],dtype='int32')
det=np.linalg.det(A)
print('det(A)={:4.1f}'.format(det))

det(A)=-11.0


In [77]:
det=np.linalg.det(A)
print('det(A)=',det)

det(A)= -11.000000000000002


In [78]:
a1=np.array([[-1,3],[2,1]])
a2=np.array([[2,3],[1,1]])
a3=np.array([[2,-1],[1,2]])
det=1*np.linalg.det(a1) - 1*np.linalg.det(a2) - 1*np.linalg.det(a3)
print('det(A)={:4.1f}'.format(det))

det(A)=-11.0
