## 대화창 실습 : numpy의 ndarray 사용

In [0]:
import numpy as np
a = np.array([1, 2, 3])  # 넘파이 ndarray 객체의 생성
a

array([1, 2, 3])

In [0]:
a.shape      # a 객체의 형태(shape)

(3,)

In [0]:
a.ndim       # a 객체의 차원

1

In [0]:
a.dtype      # a 객체 내부 자료형

dtype('int64')

In [0]:
a.itemsize   # a 객체 내부 자료형이 차지하는 메모리 크기(byte)

8

In [0]:
a.size       # a 객체의 전체 크기(항목의 수)

3

## 대화창 실습 : numpy와 데이터 형

In [0]:
a = np.array([1, 2, 3], dtype='int32')

In [0]:
b = np.array([4, 5, 6], dtype='int64')

In [0]:
a.dtype

dtype('int32')

In [0]:
b.dtype

dtype('int64')

In [0]:
c = a + b
c.dtype

dtype('int64')

###  주의 : ndarray 배열을 생성할 때 주의할 점

In [0]:
a = np.array([1, 2, 3, 4])

In [0]:
a = np.array(1, 2, 3, 4) # 잘못된 입력

ValueError: ignored

In [0]:
a = np.array([1, 'two', 3, 4], dtype=np.int32)
a

ValueError: ignored

In [0]:
a = np.array([1, 'two', 3, 4])
a

array(['1', 'two', '3', '4'], dtype='<U21')

## NOTE : 넘파이 배열의 데이터 타입을 지정하는 두 가지 방법

In [0]:
a = np.array([1, 2, 3, 4], dtype = np.int32)

In [0]:
a = np.array([1, 2, 3, 4], dtype = 'int32')

## 대화창 실습 : ndarray의 메소드

In [0]:
import numpy as np
a = np.array([1, 2, 3])  # 1차원 ndarray 배열 생성
a.max()     # 가장 큰 값을 반환

3

In [0]:
a.min()     # 가장 작은 값을 반환

1

In [0]:
a.mean()    # 평균 값을 반환

2.0

## 대화창 실습 : ndarray의 flatten() 메소드

In [0]:
a = np.array([[1, 1], [2, 2], [3, 3]])  
a.flatten()      # ndarray 배열의 평탄화 메소드

array([1, 1, 2, 2, 3, 3])

## 대화창 실습 : ndarray의 append() 함수

In [0]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.append([a], b, axis = 0)  # [a]를 통해 2차원 배열로 만들어야 함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 대화창 실습 : ndarray의 rand() 함수

In [0]:
np.random.rand(3, 3) # (3, 3) shape의 난수 생성

array([[0.07552498, 0.35947102, 0.27163194],
       [0.42807494, 0.55079932, 0.79890762],
       [0.98415269, 0.93965474, 0.51654578]])

##  대화창 실습 : ndarray의 randint() 함수

In [0]:
np.random.randint(0, 10, size = 10) # 0에서 10사이의 10개의 난수생성

array([7, 5, 0, 2, 8, 0, 7, 3, 6, 8])

## 대화창 실습 : ndarray의 덧셈(shape이 같을 경우)
 

In [0]:
a = np.array([1, 2, 3])   # 1, 2, 3 원소를 가지는 1차원 ndarray
b = np.array([4, 5, 6])   # 4, 5, 6 원소를 가지는 1차원 ndarray
c = a + b                 # 1차원 ndarray의 덧셈
c

array([5, 7, 9])

## 대화창 실습 : numpy의 ndarray의 덧셈(shape이 다를 경우)

In [0]:
a = np.array([1, 2])     # 2개의 원소를 가지는 1차원 배열 : (2,) shape
b = np.array([4, 5, 6])  # 3개의 원소를 가지는 1차원 배열 : (3,) shape
c = a + b

ValueError: ignored

## 대화창 실습 : 2차원 ndarray의 사칙연산

In [0]:
a = np.array([[1, 2], [3, 4]])   # 2차원 배열 a
b = np.array([[10,20], [30,40]]) # 2차원 배열 b
a + b

array([[11, 22],
       [33, 44]])

In [0]:
a - b

array([[ -9, -18],
       [-27, -36]])

In [0]:
a * b

array([[ 10,  40],
       [ 90, 160]])

In [0]:
a / b

array([[0.1, 0.1],
       [0.1, 0.1]])

## 대화창 실습 : 행렬 곱 함수 matmul() 실습

In [0]:
np.matmul(a, b)

array([[ 70, 100],
       [150, 220]])

In [0]:
a @ b

array([[ 70, 100],
       [150, 220]])

In [0]:
a[0,0] * b[0,0] + a[0,1] * b[1,0]

70

In [0]:
a[0,0] * b[0,1] + a[0,1] * b[1,1]

100

In [0]:
a[1,0] * b[0,0] + a[1,1] * b[1,0]

150

In [0]:
a[1,0] * b[0,1] + a[1,1] * b[1,1]

220

## 대화창 실습 : 단위행렬에 대한 행렬 곱

In [0]:
a = [[1, 2], [3, 4]]
b = [[1, 0], [0, 1]] # b는 단위행렬
np.matmul(a, b) # a행렬과 단위행렬 b의 곱의 결과

array([[1, 2],
       [3, 4]])

## 대화창 실습 : 2차원 ndarray의 덧셈, 뺄셈, 곱셈, 나눗셈, 제곱 연산

In [0]:
a = np.array([[1, 2], [3, 4]])
a + 1             # 행렬의 각 성분에 대한 덧셈

array([[2, 3],
       [4, 5]])

In [0]:
a - 1             # 행렬의 각 성분에 대한 뺄셈

array([[0, 1],
       [2, 3]])

In [0]:
a * 100           # 행렬의 각 성분에 대한 곱셈

array([[100, 200],
       [300, 400]])

In [0]:
a / 100           # 행렬의 각 성분에 대한 나눗셈

array([[0.01, 0.02],
       [0.03, 0.04]])

In [0]:
a ** 2            # 행렬의 각 성분에 대한 제곱연산

array([[ 1,  4],
       [ 9, 16]])

## 대화창 실습 : 초기값을 가지는 배열의 생성

In [0]:
np.zeros((2, 3))

In [0]:
np.ones((2, 3))

In [0]:
np.full((2, 3), 100)

In [0]:
np.eye(3)

In [0]:
np.random.random((2, 3))

## 대화창 실습 : arange() 함수를 이용한 배열 생성

In [ ]:
np.arange(0, 10)

In [0]:
np.arange(0, 10, 2)

In [0]:
np.arange(0, 10, 3)

In [0]:
np.arange(0.0, 1.0, 0.2)

## 대화창 실습 : linspace() 함수를 이용한 배열 생성

In [0]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [0]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## 대화창 실습 : reshape()을 이용한 배열의 재구성

In [0]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [0]:
np.arange(0,10).reshape(3,3)

ValueError: ignored

## 대화창 실습 : 다른 차원으로의 reshape() 실습

In [0]:
np.arange(0, 24).reshape(4, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

## 대화창 실습 : transpose() 함수

In [0]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
np.transpose(a)

array([[0, 2, 4],
       [1, 3, 5]])

## 대화창 실습 : sum 함수와 axis에 따른 원소의 합

In [0]:
a = np.arange(0,6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
a.sum() # 행렬의 모든 원소의 합

15

In [0]:
a.sum(axis = 0) # 0축 방향(행 방향) 원소의 합

array([6, 9])

## 대화창 실습 : 1축 방향 원소의 합

In [0]:
a.sum(axis = 1) # 1축 방향(열 방향) 원소의 합

array([1, 5, 9])

## 대화창 실습 : 0축과 1축 방향 원소의 최솟값 최댓값

In [0]:
a.min(axis=0) # 0축 방향 원소의 최솟값

In [0]:
a.min(axis=1) # 1축 방향 원소의 최솟값

In [0]:
a.max(axis=0) # 0축 방향 원소의 최솟값

In [0]:
a.max(axis=1) # 1축 방향 원소의 최솟값

## 대화창 실습 : ndarray의 insert() 함수

In [2]:
a = np.array([1, 3, 4])
np.insert(a, 1, 2)

array([1, 2, 3, 4])

In [3]:
a = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(a, 1, 4, axis = 0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [4]:
np.insert(a, 1, (4, 4), axis = 0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [0]:
np.insert(a, 1, 4, axis = 1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

## 대화창 실습 : 1차원 배열의 인덱싱하기

In [0]:
a = np.array([1, 2, 3])
print(a[0], a[1], a[2])

1 2 3


In [0]:
print(a[-1], a[-2], a[-3])

3 2 1


## 대화창 실습 : 1차원 배열에서 여러 개의 원소를 인덱싱하기

In [0]:
a = np.array([1, 2, 3, 4])
print(a[np.array([0, 1])])

[1 2]


In [0]:
print(a[np.array([0, 1, 2])])

[1 2 3]


In [0]:
print(a[np.array([0, 1, 3])])

[1 2 4]


In [0]:
print(a[np.array([1, 1, 1, 1])])

[2 2 2 2]


## 대화창 실습 : 리스트와 슬라이싱

In [0]:
aList = [10, 20, 30, 40, 50, 60, 70, 80]
aList[1:5]

[20, 30, 40, 50]

## 대화창 실습 : 넘파이의 슬라이싱

In [0]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
a[1:5]     # 슬라이싱 구간 [시작:끝] 인덱스

array([20, 30, 40, 50])

In [0]:
a[1:]

array([20, 30, 40, 50, 60, 70, 80])

In [0]:
a[:]        # 전체를 슬라이싱

array([10, 20, 30, 40, 50, 60, 70, 80])

In [0]:
a[::2]      # 양수 2의 스텝값

array([10, 30, 50, 70])

In [0]:
a[::-1]     # 음수 스텝값

array([80, 70, 60, 50, 40, 30, 20, 10])

## 대화창 실습 : 2차원 배열의 인덱스

In [6]:
a = np.arange(0, 6).reshape(3, 2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [7]:
print(a[0])

[0 1]


In [0]:
print(a[0, 0])

0


In [0]:
print(a[0, 1])

1


In [0]:
print(a[0, 2])

IndexError: ignored

## 대화창 실습 : 3차원 배열의 인덱스

In [0]:
a = np.arange(0, 24).reshape(4, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [0]:
print(a[1, 2, 1])

11


## 대화창 실습 : 3차원 배열의 인덱스와 concatenate() 함수

In [0]:
a = np.arange(0, 24).reshape(4, 3, 2)
a[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
a[0, 0]

array([0, 1])

In [0]:
a[0, 1]

array([2, 3])

In [0]:
a[0, 2]

array([4, 5])

In [0]:
np.concatenate((a[0, 0], a[0, 2]), axis=0)

array([0, 1, 4, 5])

# 2차원 배열의 슬라이싱

In [8]:
a = np.arange(0, 9).reshape(3, 3)
print(a)   # a를 출력해 봅시다

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
print(a[0])

[0 1 2]


In [10]:
print(a[0, :])

[0 1 2]


In [11]:
print(a[:, 0])

[0 3 6]


In [0]:
print(a[0, 0:2])

[0 1]


In [0]:
print(a[0, :2])

[0 1]


In [13]:
print(a[0:2, 0:2])

[[0 1]
 [3 4]]


In [14]:
print(a[:2, :2])

[[0 1]
 [3 4]]


In [15]:
print(a[1:, 1:])

[[4 5]
 [7 8]]


In [16]:
print(a[1, 1:])

[4 5]


In [17]:
print(a[1:2, 1:])   # 이 내용도 테스트 해 봅시다

[[4 5]]


In [0]:
a[1, 1:].shape

(2,)

In [0]:
a[1:2, 1:].shape

(1, 2)

# 코드 11-1 : 선형 연립 방정식 풀이
## numpy_linear_ex.py

In [0]:
import numpy as np

a = np.array([[2, 3], [1, -2]])
b = np.array([1, 4])
x = np.linalg.solve(a, b)

print(x)

[ 2. -1.]


In [0]:
b = np.array([4, 5, 6])
b

## 대화창 실습 : linalg.det() 함수를 사용한 행렬식

In [18]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

In [19]:
b = np.array([[1, 2], [3, -6]])
np.linalg.det(b)

-12.0

In [20]:
b = np.array([[1, 2], [1, 2]])
np.linalg.det(b)

0.0